version: "2"
services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # RabbitMQ standard port
      - "15672:15672" # RabbitMQ management UI port
    networks:
      - default

networks:
  default:
    external:
      name: microservice_network
